### ISSUE TITLE
warn, not fail, on non-auth in sbtools_GET

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/sbtools#134]
Public information should be accessible via sbtools_GET without authentication, but `sbtools_GET` currently calls `check_session(session)` on the second line, and `check_session(session)` calls `stop()` if the session isn't authenticated. I propose a second argument to check_session, `on_fail`, that accepts either `stop` or `warning` and then uses that function to sound the alarm. Then sbtools_GET could call `check_session(session, warning)` whereas other REST_helpers could call `check_session(session)` where the default is `on_fail=stop`.

This gets at the somewhat thorny, recurring issue of how to alert the user when they're not logged in but maybe want to be, e.g., when they're searching for something and they don't find it, and we don't know if that's because it doesn't exist or because they're not logged in. How can we best help the user in that case?

This is related to issue  #118 and discussion in PR #133

**Comment by aappling-usgs** [comment]
The coding is easy, but I'd like thoughts from others before I do anything because this is a big API thing - @lawinslow , @sckott , @jread-usgs ?

**Comment by jread-usgs** [comment]
I think GET should be a little different, because `sbtools` should be useful for people who just want to find and download public data. They shouldn't need an account, so I would like to support that use case. 

I think GET used to do something along the lines of verify the session was either NULL or valid, and then try the GET. So, users that aren't logged in are NULL, and this worked unless you hit a private item, in which case you didn't know if the issue was because you weren't logged in or the item didn't exist. Curious how others think this should work. Didn't really like the old way, but it made public data pass through cleanly.

**Comment by aappling-usgs** [comment]
Yeah, even a warning is a bit strong when the data are actually public and can be found, isn't it? I'm now wondering if we could just delete the `check_session(session)` line from `sbtools_GET`, because `handle_errors` already stops with `"check authorization and/or content"` if there's a problem.

**Comment by sckott** [comment]
I think it makes sense to delete. Just tested removing the check line now, which means public items work fine, and private gives e.g., 

```r
item_get('55569325e4b0a92fa7e9cf36')
#> Error: Item not found for ID=55569325e4b0a92fa7e9cf36. Either the item does not exist or the item is #> secured and requires authentication to access.
```
