### ISSUE TITLE
NetCDF files are uploading as "extensions" and not as "files"

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/sbtools#273]
This may be a recent change in SB services and handling of these files. But it makes it challenging to rely on functions like `item_list_files()` since extensions don't show up there

![image](https://user-images.githubusercontent.com/2349007/111186059-a24a0480-8580-11eb-95a5-e6c0cb79631b.png)

**Comment by dblodgett-usgs** [comment]
I wonder if there is a way to turn off extension creation. Will ping the ScienceBase team to see what we might be able to do.

**Comment by dblodgett-usgs** [comment]
I actually think this might be a bug on the SB side. I just uploaded a netcdf file and it created an OPeNDAP extension -- it shouldn't be doing that. Will see what I hear back from them.

**Comment by jread-usgs** [comment]
Would be good if this also keeps .xml FGDC metadata working as-is 👍

**Comment by dblodgett-usgs** [comment]
How do you feel about defaulting to scrape contents by default (the current behavior) but raise a message alerting the user that the file isn't in downloads if it doesn't end up in there after the upload is complete? e.g. in the .nc case, you would get a message saying the file got put into an extension rather than the item files.

**Comment by jread-usgs** [comment]
That would make sense to me, and/or perhaps we create a warning message that we'd be changing the default behavior in the future to _not_ scrape unless arg is TRUE(?) and update that in the future to with a minor version change since I do agree it probably makes more sense to upload the file w/o fancy conversions as default. 

I'm also assuming in your proposal that I could use an arg to specify that I don't want the .nc file turned into an extension?

**Comment by dblodgett-usgs** [comment]
```r
> item <- item_upload_create("4f7afec1e4b0b2f259355f30", "example_huc_eta.nc")
#> Warning message:
#> In check_upload(item, files) : Not all files ended up in the item files. 
#> This indicates that a sciencebase extension was created with the file. 
#> set 'scrape_files' to FALSE to avoid this behavior. 
#> NOTE: 'scrape_files' will default to FALSE in a future version of sbtools.
```

Yeah?

**Comment by jread-usgs** [comment]
I don't know if `scrape_files` is an intuitive arg name for SB users. It is what the service is doing I guess, but perhaps "sb_extension" or something else? 
Also I think it should have a default of single boolean but also support a vector of booleans of the same length of the vector of file names.

**Comment by dblodgett-usgs** [comment]
yeah... I had the same sense. In some cases it adds extensions, in other cases, it just pulls metadata out (xml). I used that parameter to be consistent with the python package and actual SB services. 

The vector option is a little complicated. We would have to iterate over the file list rather than upload a multi-file-body as is done now since this is a per-sb-call parameter. I think I'd rather push the iteration on the option up to the client rather than doing the iteration down in this function. That ok?

**Comment by jread-usgs** [comment]
Understood, I see. I think that makes sense to me
